### ISSUE TITLE
Installation Failed using pip.

### ISSUE THREAD

**Issue by pa4373** [berniey/hanziconv#1]
It produces the following error message when I launched `pip install hanziconv`:
```
Downloading/unpacking hanziconv
  Downloading hanziconv-0.2.2.tar.gz (193kB): 193kB downloaded
  Running setup.py (path:/XXXXXXX/dev_env/build/hanziconv/setup.py) egg_info for package hanziconv
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/XXXXXXX/dev_env/build/hanziconv/setup.py", line 6, in <module>
        from hanziconv import __version__, __author__
      File "hanziconv/__init__.py", line 54
    SyntaxError: Non-ASCII character '\xe7' in file hanziconv/__init__.py on line 55, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/XXXXXXX/dev_env/build/hanziconv/setup.py", line 6, in <module>

    from hanziconv import __version__, __author__

  File "hanziconv/__init__.py", line 54

SyntaxError: Non-ASCII character '\xe7' in file hanziconv/__init__.py on line 55, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /XXXXXXX/dev_env/build/hanziconv
Storing debug log for failure in /YYYYYY/.pip/pip.log
```
which can be fixed by simply moving `# -*- coding: utf-8 -*-$` back to the first line in `hanziconv/__init__.py`

Tested with Python 2.7.9, OS X 10.10.

**Comment by berniey** [comment]
I did not encounter such error on Mac.  But I'll put the line back to first line in next release.  Thx
